const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';

const USER_LOGOUT_SUCCESS = 'USER_LOGOUT_SUCCESS';

const USER_LOGIN_FAILURE = 'USER_LOGIN_FAILURE';

export { USER_LOGIN_SUCCESS, USER_LOGOUT_SUCCESS, USER_LOGIN_FAILURE };
